# Generated by Django 4.1.7 on 2023-08-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_product_alter_user_id_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=50),
        ),
    ]
