# Generated by Django 4.1.7 on 2023-08-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='WatchList',
            field=models.ManyToManyField(blank=True, related_name='user', to='auctions.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
