# Generated by Django 4.1.7 on 2023-08-08 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_watchlist_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='winner',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm', models.CharField(max_length=250)),
                ('comm_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('prod', models.ManyToManyField(blank=True, related_name='comment', to='auctions.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
