# Generated by Django 4.1.5 on 2023-08-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_user_product_closed_product_winner_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='winner',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
