# Generated by Django 4.1.5 on 2023-08-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_product_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='winner',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
